site_name: Ingemasoft Centro de Ayuda
site_description: Centro de Ayuda para el software empresarial Ingemasoft
site_author: IMS Global

# Carpeta donde están tus .md
docs_dir: docs

# Carpeta de salida (sitio estático)
site_dir: site

# Configuración del tema Material
theme:
  name: material
  language: es
  logo: assets/img/logo_ims_blanco.png   # (opcional) ruta a tu logo
  favicon: assets/img/favicon-32.png
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Modo claro

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - toc.integrate
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - header.autohide
    - content.image.lightbox                         # zoom en imágenes (si tu versión lo soporta)


# Plugins activos
plugins:
  - search                # búsqueda interna
  - mermaid2              # para diagramas Mermaid

markdown_extensions:
  - admonition
  - pymdownx.details      # para los colapsables "???"
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/css/ims-overrides.css
  - assets/css/ims-colors.css



# Navegación principal (ajusta según tus archivos)
nav:
  - Home: index.md
  - Pyme:
      - Empieza aquí: pyme/index.md
      - Procesos básicos:
          - Crear cliente: pyme/basicos/crear-cliente.md
          - Facturar: pyme/basicos/facturar.md
          - Compras: pyme/basicos/compras.md
          - Inventario: pyme/basicos/inventario.md
      - Procesos adicionales:
          - Notas débito/crédito: pyme/adicionales/nd-nc.md
          - Cuentas por cobrar: pyme/adicionales/cxc.md
          - Cuentas por pagar: pyme/adicionales/cxp.md
  - Hotel:
      - Empieza aquí: hotel/index.md
      - Procesos básicos:
          - Check-in/Facturación: hotel/basicos/checkin-facturacion.md
          - Compras: hotel/basicos/compras.md
          - Inventario: hotel/basicos/inventario.md
      - Procesos adicionales:
          - Cuentas por cobrar: hotel/adicionales/cxc.md
          - Cuentas por pagar: hotel/adicionales/cxp.md
  - Telco:
      - Empieza aquí: telco/index.md
      - Procesos básicos:
          - Clientes/Activaciones: telco/basicos/clientes-activaciones.md
          - Facturar: telco/basicos/facturar.md
          - Inventario: telco/basicos/inventario.md
      - Procesos adicionales:
          - Cuentas por cobrar: telco/adicionales/cxc.md
          - Cuentas por pagar: telco/adicionales/cxp.md
  - Novedades: updates/index.md




#nav:
#  - Overview: 01-overview.md
#  - Arquitectura: 02-Arquitectura.md
#  - Setup: 03-Setup.md
#  - Desarrollo: 04-desarrollo.md
#  - Guias v1:
#    - Modulo Ventas:
#      - Crear cliente: 05-Guias/v1/Ventas/crear-clientes.md
#      - Factura electrónica (NDE): 05-Guias/v1/Ventas/factura-nde.md
#      - Devoluciones / NCE:
#        - Guia principal: 05-Guias/v1/Ventas/nce/index.md
#      - Factura POS: 05-Guias/v1/Ventas/factura-pos.md
#      - Nota crédito electrónica (NCE): 05-Guias/v1/Ventas/nota-credito-nce.md
#    - Modulo Compras:
#      - Compras: 05-Guias/v1/Compras/Compras.md
#  - Esquema del Metadata Schema: 06-metadata-esquema.md
#  - Colaboración: 07-Colaboracion.md
#  - Changelog: 08-changelog.md