site_name: Ingemasoft Centro de Ayuda
site_description: Centro de Ayuda para el software empresarial Ingemasoft
site_author: Equipo Ingemasoft

# Carpeta donde están tus .md
docs_dir: docs

# Carpeta de salida (sitio estático)
site_dir: site

# Configuración del tema Material
theme:
  name: material
  logo: assets/img/logo_ims_blanco.png   # (opcional) ruta a tu logo
  ##favicon: assets/diagrams/favicon.png

# Plugins activos
plugins:
  - search                # búsqueda interna
  - mermaid2              # para diagramas Mermaid


# Navegación principal (ajusta según tus archivos)
nav:
  - Overview: 01-overview.md
  - Arquitectura: 02-Arquitectura.md
  - Setup: 03-setup.md
  - Desarrollo: 04-desarrollo.md
  - Guias v1:
    - Modulo Ventas:
      - Crear cliente: 05-Guias/v1/Ventas/crear-clientes.md
      - Factura electrónica (NDE): 05-Guias/v1/Ventas/factura-nde.md
      - Factura POS: 05-Guias/v1/Ventas/factura-pos.md
      - Nota crédito electrónica (NCE): 05-Guias/v1/Ventas/nota-credito-nce.md
    - Modulo Compras:
      - Compras: 05-Guias/v1/Compras/Compras.md
  - Esquema del Metadata Schema: 06-metadata-schema.md
  - Colaboración: 07-contributing.md
  - Changelog: 08-changelog.md