site_name: Ingemasoft Centro de Ayuda
site_description: Centro de Ayuda para el software empresarial Ingemasoft
site_author: IMS Global
site_url: https://ingemagsoft.github.io/Centro_de_Ayuda_IMS/
repo_url: https://github.com/ingemagsoft/Centro_de_Ayuda_IMS
repo_name: IMS Centro de Ayuda

# Carpeta donde están tus .md
docs_dir: docs

# Carpeta de salida (sitio estático)
site_dir: site

# Configuración del tema Material
theme:
  name: material
  language: es
  logo: assets/img/logos/logo_ims_blanco.png   # (opcional) ruta a tu logo
  favicon: assets/img/favicon-32.png
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Modo claro

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    #- toc.integrate
    - toc.sidebar
    - navigation.top
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - header.autohide
    - content.image.lightbox                         # zoom en imágenes (si tu versión lo soporta)


# Plugins activos
plugins:
  - search                # búsqueda interna
  - mermaid2              # para diagramas Mermaid
  - social:
      enabled: !ENV [IMS_SOCIAL, false]   # OFF por defecto (si variable de entorno IMS_SOCIAL está a true, se activa)
      cards_layout_options:
        color: "#0F6CBD"
        background_color: "#0F6CBD"
        text_color: "#FFFFFF"
        logo: assets/img/logos/logo_ims_blanco.png


markdown_extensions:
  - admonition
  - pymdownx.details      # para los colapsables "???"
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/css/ims-overrides.css
  - assets/css/ims-colors.css

extra_javascript:
  - assets/js/ims-ux.js
  - assets/js/ims-local-search.js   # búsqueda local personalizada

# Navegación principal (ajusta según tus archivos)
nav:
  - Home: index.md
  - Pyme:
      - Empieza aquí: pyme/index.md
      - Parametrizacion:
          - Fichas:
            - Crear cliente: 05-Guias/v1/Ventas/crear-clientes.md
            - Facturar (NDE): 05-Guias/v1/Ventas/factura-nde.md
            - Facturar en POS: 05-Guias/v1/Ventas/factura-pos.md
      #    - Productos:
      #      - Listas de precios: 05-Guias/v1/Ventas/listas-precios.md
      #      - Tipos de listas: 05-Guias/v1/Ventas/tipos-listas.md
      #      - Listas de costos: 05-Guias/v1/Ventas/listas-costos.md
      #- Inventario y facturacion:
      #    - Facturacion:
      #      - Facturar en POS: 05-Guias/v1/Ventas/factura-pos.md
      #      - Facturar (NDE): 05-Guias/v1/Ventas/factura-nde.md
      #      - Crear cliente: 05-Guias/v1/Ventas/crear-clientes.md
      #      - Nota crédito (hub): 05-Guias/v1/Ventas/nce/index.md            
      #    - Inventario:
      #      - Compras POS: 05-Guias/v1/Ventas/listas-precios.md
      #      - Entrada de mercancia: 05-Guias/v1/Ventas/tipos-listas.md
      #      - Salida de mercancia: 05-Guias/v1/Ventas/listas-costos.md
      #- Informes:
      #    - Inf. Mto productos x ventas: 06-Informes/v1/Productos/mto-productos-x-ventas.md
      #    - Inf. de documentos: 06-Informes/v1/Documentos/inf-documentos.md
      #    - Inf. Kardex: 06-Informes/v1/Inventario/inf-kardex.md
      #    - Inf. Inventario: 06-Informes/v1/Inventario/inf-inventario.md
      #    - Inf. Mto de terceros: 06-Informes/v1/Terceros/mto-terceros.md
      - Procesos adicionales:
          - Nota crédito (hub): 05-Guias/v1/Ventas/nce/index.md
          - Nota crédito – Contado (ref): 05-Guias/v1/Ventas/nce/contado-ref.md
          - Nota crédito – Contado (sin ref): 05-Guias/v1/Ventas/nce/contado-sin-ref.md
          - Nota crédito – Crédito (ref): 05-Guias/v1/Ventas/nce/credito-ref.md
          - Nota crédito – Crédito (sin ref): 05-Guias/v1/Ventas/nce/credito-sin-ref.md
  - Hotel:
      - Empieza aquí: hotel/index.md
  - Telco:
      - Empieza aquí: telco/index.md
  - Novedades: updates/index.md
  # Solo interno (no incluir en el público)
  - Proyecto (interno):
      - Overview: 01-overview.md
      - Arquitectura: 02-Arquitectura.md
      - Setup: 03-Setup.md
      - Desarrollo: 04-desarrollo.md
      - Metadata Schema: 06-metadata-esquema.md
      - Colaboración: 07-Colaboracion.md
      - Changelog: 08-changelog.md