site_name: Ingemasoft Centro de Ayuda
site_description: Centro de Ayuda para el software empresarial Ingemasoft
site_author: Equipo Ingemasoft

# Carpeta donde están tus .md
docs_dir: docs

# Carpeta de salida (sitio estático)
site_dir: site

# Configuración del tema Material
theme:
  name: material
  language: es
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  logo: assets/img/logo_ims_blanco.png   # (opcional) ruta a tu logo
  favicon: assets/img/favicon-32.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - toc.integrate
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - header.autohide

# Plugins activos
plugins:
  - search                # búsqueda interna
  - mermaid2              # para diagramas Mermaid

markdown_extensions:
  - admonition
  - pymdownx.details      # para los colapsables "???"
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - styles/ims-overrides.css



# Navegación principal (ajusta según tus archivos)
nav:
  - Overview: 01-overview.md
  - Arquitectura: 02-Arquitectura.md
  - Setup: 03-Setup.md
  - Desarrollo: 04-desarrollo.md
  - Guias v1:
    - Modulo Ventas:
      - Crear cliente: 05-Guias/v1/Ventas/crear-clientes.md
      - Factura electrónica (NDE): 05-Guias/v1/Ventas/factura-nde.md
      - Devoluciones / NCE:
        - Guia principal: 05-Guias/v1/Ventas/nce/index.md
      - Factura POS: 05-Guias/v1/Ventas/factura-pos.md
      - Nota crédito electrónica (NCE): 05-Guias/v1/Ventas/nota-credito-nce.md
    - Modulo Compras:
      - Compras: 05-Guias/v1/Compras/Compras.md
  - Esquema del Metadata Schema: 06-metadata-esquema.md
  - Colaboración: 07-Colaboracion.md
  - Changelog: 08-changelog.md